name: air_medical_station
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

##SECTION --Dependencies
dependencies:
  flutter:
    sdk: flutter

  ## t2 -- Presentation
  loading_animation_widget: ^1.2.0+4
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  flutter_icons_plus: ^1.0.3
  flex_color_scheme: ^7.0.4
  octo_image: ^2.0.0
  font_awesome_flutter: ^10.7.0
  flutter_easyloading: ^3.0.5
  flutter_snackbar_plus: ^0.5.0
  auto_animated_list: ^1.0.4
  solid_bottom_sheet: ^0.1.10
  theme_manager: ^2.0.4
  flutter_zoom_drawer: ^3.0.4+1

  ## t2 -- Providers
  cloud_firestore: ^5.0.2
  firebase_database: ^11.0.2

  ## t2 -- Services
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  logger: ^2.3.0
  min_id: ^1.1.0
  intl: ^0.19.0
  form_controller: ^0.8.4
  firebase_crashlytics: ^4.0.2
  permission_handler: ^11.3.1
  dio: ^5.0.0
  google_fonts: ^6.2.1
  agora_uikit: ^1.3.10
  zego_uikit_prebuilt_call: ^4.16.12
  zego_uikit_signaling_plugin: ^2.8.2
  ## t2 -- Firebase
  #  firebase: ^9.0.2
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0
  image_picker: ^1.0.4
  file_picker: ^8.0.7
  syncfusion_flutter_gauges: ^27.1.55

##!SECTION --Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - dev.env
    - prod.env